### ISSUE TITLE
Roadmap: v1.0.0

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-aggregator#1]
v1.0.0 High Level Requirements

- [x] [Database of remote farmOS URLs](https://github.com/farmOS/farmOS-aggregator/issues/2)
- [x] [Web UI for viewing and managing database](https://github.com/farmOS/farmOS-aggregator/issues/3)
- [x] [Ability to add new farmOS URLs to database via web UI](https://github.com/farmOS/farmOS-aggregator/issues/4)
- [x] [Authenticate and store credentials for each farmOS URL](https://github.com/farmOS/farmOS-aggregator/issues/5)
- [x] [Provide API for pushing/pulling data to/from multiple farmOS instances in bulk](https://github.com/farmOS/farmOS-aggregator/issues/6)
- [x] [Basic authentication for web UI and API](https://github.com/farmOS/farmOS-aggregator/issues/7)

Prerequisites:

- [x] [farmOS.py](https://github.com/farmOS/farmOS.py)

**Comment by mstenta** [comment]
I'm leaning towards using Sqlite3 + Flask + Flask Admin (Python) for this.

Reasoning:

- I'm familiar with it.
- Covers most of the requirements above out of the box.
- Python is widely used in the data sciences, so this system could be extended in the future to provide some tools for more advanced data aggregation and processing in the future.
- Minimal dependencies / Python ecosystem is relatively stable and unchanging.

**Comment by mstenta** [comment]
This will depend on development of https://github.com/farmOS/farmOS.py for the ability to communicate with individual farmOS instances via API.

**Comment by mstenta** [comment]
It may also be a good opportunity to implement and OAuth2 identity provider service within farmOS that we can use to authenticate with, instead of storing raw login credentials.

**Comment by mstenta** [comment]
See also: [Roamap for v1.1.0](https://github.com/farmOS/farmOS-aggregator/milestone/2) - I'm putting stuff in there that is not necessarily a requirement for the minimum viable product (v1.0.0). It may change.

**Comment by paul121** [comment]
Currently, the aggregator meets all of these requirements. A lot of the requirements were covered by using the Fast-API Full Stack Cookie-Cutter project. 

I'm going to close this issue and move on to tracking the next batch of features in [Roadmap for v1.1.0](https://github.com/farmOS/farmOS-aggregator/milestone/2)
