### ISSUE TITLE
Roadmap: v1.1.0

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-aggregator#8]
- [ ] [OAuth Support](https://github.com/farmOS/farmOS-aggregator/issues/20)
- [ ] Support for tracking basic farmOS metrics #22 
- [ ] [Ansible playbook for provisioning a remote server](https://github.com/farmOS/farmOS-aggregator/issues/9)
- [ ] [Automate SSL certificates with Let's Encrypt](https://github.com/farmOS/farmOS-aggregator/issues/10)
- [ ] Create a Vagrant file for testing production environment #21

**Comment by mstenta** [comment]
Closing this - we're organizing using the milestone.
